version: '3.9'

networks:
  mongo:
    external: true

services:

  mongo-1:
    image: mongo:4.4.16
    container_name: dev_study_mongo_1
    restart: always
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      mongo:
        ipv4_address: 172.19.0.3
    ports:
      - 127.0.0.1:27018:27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/mongo:/data/db
      - ./logs/mongo:/var/log/mongodb
