version: "3.9"
services:

  redis_9201:
    image: redis:6.2
    container_name: dev_study_redis_9201
    command: ['redis-server', '/etc/redis/redis.conf']
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/redis_cluster/redis_9201.conf:/etc/redis/redis.conf
      - ./conf/tls:/tls
      - ./data/redis_cluster/9201/data:/data

  redis_9202:
    image: redis:6.2
    container_name: dev_study_redis_9202
    command: ['redis-server', '/etc/redis/redis.conf']
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/redis_cluster/redis_9202.conf:/etc/redis/redis.conf
      - ./conf/tls:/tls
      - ./data/redis_cluster/9202/data:/data

  redis_9203:
    image: redis:6.2
    container_name: dev_study_redis_9203
    command: ['redis-server', '/etc/redis/redis.conf']
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/redis_cluster/redis_9203.conf:/etc/redis/redis.conf
      - ./conf/tls:/tls
      - ./data/redis_cluster/9203/data:/data

  redis_9204:
    image: redis:6.2
    container_name: dev_study_redis_9204
    command: ['redis-server', '/etc/redis/redis.conf']
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/redis_cluster/redis_9204.conf:/etc/redis/redis.conf
      - ./conf/tls:/tls
      - ./data/redis_cluster/9204/data:/data

  redis_9205:
    image: redis:6.2
    container_name: dev_study_redis_9205
    command: ['redis-server', '/etc/redis/redis.conf']
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/redis_cluster/redis_9205.conf:/etc/redis/redis.conf
      - ./conf/tls:/tls
      - ./data/redis_cluster/9205/data:/data

  redis_9206:
    image: redis:6.2
    container_name: dev_study_redis_9206
    command: ['redis-server', '/etc/redis/redis.conf']
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/redis_cluster/redis_9206.conf:/etc/redis/redis.conf
      - ./conf/tls:/tls
      - ./data/redis_cluster/9206/data:/data
