version: "3.9"
services:

  node-9201:
    image: redis:6.2
    container_name: redis-cluster-node-9201
    command: ['redis-server', '/etc/redis/redis.conf']
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/configs/node-9201.conf:/etc/redis/redis.conf
      - ./conf/tls:/tls
      - ./data/node-9201/data:/data

  node-9202:
    image: redis:6.2
    container_name: redis-cluster-node-9202
    command: ['redis-server', '/etc/redis/redis.conf']
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/configs/node-9202.conf:/etc/redis/redis.conf
      - ./conf/tls:/tls
      - ./data/node-9202/data:/data

  node-9203:
    image: redis:6.2
    container_name: redis-cluster-node-9203
    command: ['redis-server', '/etc/redis/redis.conf']
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/configs/node-9203.conf:/etc/redis/redis.conf
      - ./conf/tls:/tls
      - ./data/node-9203/data:/data

  node-9204:
    image: redis:6.2
    container_name: redis-cluster-node-9204
    command: ['redis-server', '/etc/redis/redis.conf']
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/configs/node-9204.conf:/etc/redis/redis.conf
      - ./conf/tls:/tls
      - ./data/node-9204/data:/data

  node-9205:
    image: redis:6.2
    container_name: redis-cluster-node-9205
    command: ['redis-server', '/etc/redis/redis.conf']
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/configs/node-9205.conf:/etc/redis/redis.conf
      - ./conf/tls:/tls
      - ./data/node-9205/data:/data

  node-9206:
    image: redis:6.2
    container_name: redis-cluster-node-9206
    command: ['redis-server', '/etc/redis/redis.conf']
    restart: always
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/configs/node-9206.conf:/etc/redis/redis.conf
      - ./conf/tls:/tls
      - ./data/node-9206/data:/data
