version: "3.9"

networks:
  xxxxx_net:
    external: true

services:
  db:
    image: mysql:8.0.29
    container_name: xxxxx_db
    restart: always
    networks:
      xxxxx_net:
        ipv4_address: "172.24.0.3"
    ports:
      - 8563:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/mysql:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - MYSQL_DATABASE=xxxxx
      - MYSQL_ROOT_PASSWORD=bugaosuni

  emqx-1:
    image: emqx/emqx:4.4.9
    container_name: dev_study_emqx_1
    restart: always
    networks:
      xxxxx_net:
        ipv4_address: "172.24.0.4"
    ports:
      - 9800:18083
      - 9801:1883
      - 9802:8883
      - 9803:8083
      - 9804:8084
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/emqx-1/etc/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./conf/emqx-1/etc/acl.conf:/opt/emqx/etc/acl.conf
      - ./conf/emqx-1/etc/certs:/opt/emqx/etc/certs
      - ./conf/emqx-1/etc/plugins/emqx_auth_mnesia.conf:/opt/emqx/etc/plugins/emqx_auth_mnesia.conf
      - ./conf/emqx-1/etc/plugins/emqx_auth_jwt.conf:/opt/emqx/etc/plugins/emqx_auth_jwt.conf
      - ./conf/emqx-1/data/loaded_plugins:/opt/emqx/data/loaded_plugins

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: xxxxx_rabbitmq
    hostname: xxxxx_rabbitmq-1
    restart: always
    networks:
      xxxxx_net:
        ipv4_address: "172.24.0.5"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

  redis:
    image: redis:6.2-alpine
    container_name: xxxxx_redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    restart: always
    networks:
      xxxxx_net:
        ipv4_address: "172.24.0.6"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/redis/redis.conf:/etc/redis/redis.conf
      - ./data/redis/data:/data

  api:
    container_name: xxxxx_api
    image: "xxxxx_api:latest"
    build: "./xxxxx_api"
    command: /bin/bash ./docker-entrypoint.sh
    restart: always
    networks:
      xxxxx_net:
        ipv4_address: "172.24.0.20"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./xxxxx_api:/home/project
      - ./conf/api/product.local.toml:/home/project/conf/product.local.toml
      - ./logs/api:/home/logs
    depends_on:
      - db
      - rabbitmq
      - redis
      - emqx

  nginx:
    image: panla/nginx-live-server:no-ffmpeg
    container_name: xxxxx_nginx
    restart: always
    networks:
      xxxxx_net:
        ipv4_address: 172.24.0.2
    ports:
      - 8562:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
