version: "3.9"
services:
    es:
        image: "elasticsearch:7.12.0"
        restart: always
        ports:
            - 19200:9200
            - 19300:9300
        networks:
            es:
                ipv4_address: "172.19.0.4"
        environment:
            TZ: Asia/Shanghai
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
            ES_JAVA_OPTS: "-Xms256m -Xmx256m"
            discovery.type: single-node
    kibana:
        image: "kibana:7.12.0"
        restart: always
        ports:
            - 15601:5601
        networks:
            es:
                ipv4_address: "172.19.0.5"
        environment:
            ELASTICSEARCH_HOSTS: "http://172.19.0.4:9200"
            TZ: Asia/Shanghai
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
        depends_on:
            - es
networks:
    es:
        external: true
