version: "3.9"
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: dev_jenkins
    networks:
      dev_net:
        ipv4_address: 172.20.0.6
    restart: always
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/opt/docker/bin/docker:/usr/bin/docker
    environment:
      - TZ=Asia/Shanghai
networks:
  dev_net:
    external: true