version: "3.9"
services:
  es1:
    container_name: es1
    image: elasticsearch:7.12.0
    restart: always
    ports:
      - 19200:9200
      - 19300:9300
    networks:
      es:
        ipv4_address: 172.18.0.3
    volumes:
      - ./data/es1:/usr/share/elasticsearch/data
      - ./logs/es1:/usr/share/elasticsearch/logs
      - ./plugins/es1:/usr/share/elasticsearch/plugins
    environment:
      - TZ=Asia/Shanghai
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - node.name=es1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=172.18.0.4, 172.18.0.5
      - cluster.initial_master_nodes=172.18.0.3, 172.18.0.4, 172.18.0.5
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
  es2:
    container_name: es2
    image: elasticsearch:7.12.0
    restart: always
    networks:
      es:
        ipv4_address: 172.18.0.4
    volumes:
      - ./data/es2:/usr/share/elasticsearch/data
      - ./logs/es2:/usr/share/elasticsearch/logs
      - ./plugins/es2:/usr/share/elasticsearch/plugins
    environment:
      - TZ=Asia/Shanghai
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - node.name=es2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=172.18.0.3, 172.18.0.5
      - cluster.initial_master_nodes=172.18.0.3, 172.18.0.4, 172.18.0.5
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
  es3:
    container_name: es3
    image: elasticsearch:7.12.0
    restart: always
    networks:
      es:
        ipv4_address: 172.18.0.5
    volumes:
      - ./data/es3:/usr/share/elasticsearch/data
      - ./logs/es3:/usr/share/elasticsearch/logs
      - ./plugins/es3:/usr/share/elasticsearch/plugins
    environment:
      - TZ=Asia/Shanghai
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - node.name=es3
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=172.18.0.3, 172.18.0.4
      - cluster.initial_master_nodes=172.18.0.3, 172.18.0.4, 172.18.0.5
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
  kibana:
    container_name: kibana
    image: kibana:7.12.0
    restart: always
    ports:
      - 15601:5601
    networks:
      es:
        ipv4_address: 172.18.0.2
    environment:
      TZ: "Asia/Shanghai"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      ELASTICSEARCH_HOSTS: "http://172.18.0.3:9200"
    depends_on:
      - es1

networks:
  es:
    external: true
