version: "3.9"
services:
  db:
    image: postgres:13.3
    container_name: pgsql_133
    volumes:
      - ./data/pgsql/data:/var/lib/postgresql/data
    networks:
      dev_net:
        ipv4_address: 172.20.0.4
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=study

networks:
  dev_net:
    external: true
