version: "3.9"
services:
  es_11:
    image: elasticsearch:7.17.0
    container_name: dev_study_es_11
    restart: always
    networks:
      dev_net:
        ipv4_address: 172.20.3.3
    ports:
      - 20301:9200
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/es_cluster/es_11/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./conf/es_cluster/es_11/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./data/es_cluster/es_11/data:/usr/share/elasticsearch/data
      - ./data/es_cluster/es_11/plugins:/usr/share/elasticsearch/plugins
      - ./logs/es_11:/usr/share/elasticsearch/logs
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es_12:
    image: elasticsearch:7.17.0
    container_name: dev_study_es_12
    restart: always
    networks:
      dev_net:
        ipv4_address: 172.20.3.4
    ports:
      - 20302:9200
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/es_cluster/es_12/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./conf/es_cluster/es_12/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./data/es_cluster/es_12/data:/usr/share/elasticsearch/data
      - ./data/es_cluster/es_12/plugins:/usr/share/elasticsearch/plugins
      - ./logs/es_12:/usr/share/elasticsearch/logs
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es_13:
    image: elasticsearch:7.17.0
    container_name: dev_study_es_13
    restart: always
    networks:
      dev_net:
        ipv4_address: 172.20.3.5
    ports:
      - 20303:9200
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/es_cluster/es_13/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./conf/es_cluster/es_13/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./data/es_cluster/es_13/data:/usr/share/elasticsearch/data
      - ./data/es_cluster/es_13/plugins:/usr/share/elasticsearch/plugins
      - ./logs/es_13:/usr/share/elasticsearch/logs
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.17.0
    container_name: dev_study_kibana
    restart: always
    ports:
      - 20300:5601
    networks:
      dev_net:
        ipv4_address: 172.20.3.2
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      ELASTICSEARCH_HOSTS: "http://172.20.3.3:9200"
    depends_on:
      - es_11

networks:
  dev_net:
    external: true
