version: '3.9'

networks:
  mq_net:
    external: true

services:

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: dev_study_rabbitmq_1
    restart: always
    hostname: myRabbitmq-1
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    networks:
      mq_net:
        ipv4_address: "172.21.0.2"
    ports:
      - 127.0.0.1:15673:15672
      - 127.0.0.1:15672:5672
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/lib/rabbitmq
