version: '3.9'
services:

  rabbitmq-11:
    image: rabbitmq:3.8-management
    container_name: dev_study_rabbitmq_11
    restart: always
    hostname: myNode-11
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/rabbitmq_cluster/erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./data/rabbitmq_cluster/rabbitmq-11:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - ERLANG_COOKIE=MQCluster
    networks:
      dev_net:
        ipv4_address: 172.20.1.2
    ports:
      - 20100:15672
      - 20101:5672

  rabbitmq-12:
    image: rabbitmq:3.8-management
    container_name: dev_study_rabbitmq_12
    restart: always
    hostname: myNode-12
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - ERLANG_COOKIE=MQCluster
    networks:
      dev_net:
        ipv4_address: 172.20.1.3
    ports:
      - 20102:5672
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/rabbitmq_cluster/erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./data/rabbitmq_cluster/rabbitmq-12:/var/lib/rabbitmq
    depends_on:
      - rabbitmq-11

  rabbitmq-13:
    image: rabbitmq:3.8-management
    container_name: dev_study_rabbitmq_13
    restart: always
    hostname: myNode-13
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - ERLANG_COOKIE=MQCluster
    networks:
      dev_net:
        ipv4_address: 172.20.1.4
    ports:
      - 20103:5672
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/rabbitmq_cluster/erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./data/rabbitmq_cluster/rabbitmq-13:/var/lib/rabbitmq
    depends_on:
      - rabbitmq-11

networks:
  dev_net:
    external: true
