version: "3.9"
services:

  emqx_01:
    image: emqx/emqx:4.3.15
    container_name: dev_study_emqx_01
    restart: always
    networks:
      custom_net:
        ipv4_address: "172.25.0.4"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/emqx/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./conf/emqx/emqx_auth_mnesia.conf:/opt/emqx/etc/plugins/emqx_auth_mnesia.conf
      - ./conf/emqx/emqx_auth_jwt.conf:/opt/emqx/etc/plugins/emqx_auth_jwt.conf
      - ./conf/emqx/loaded_plugins:/opt/emqx/data/loaded_plugins
    environment:
      - EMQX_NODE_NAME=emqx@172.25.0.4

networks:
  custom_net:
    external: true
