version: "3.9"
services:

  emqx-1:
    image: emqx/emqx:4.3.15
    container_name: dev_study_emqx-1
    restart: always
    networks:
      dev_net:
        ipv4_address: "172.20.7.3"
    ports:
      - 9110:4370
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/loaded/loaded_plugins:/opt/emqx/data/loaded_plugins
      - ./conf/plugins/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
      - ./conf/plugins/emqx_auth_jwt.conf:/opt/emqx/etc/plugins/emqx_auth_jwt.conf
      - ./conf/plugins/emqx_auth_mnesia.conf:/opt/emqx/etc/plugins/emqx_auth_mnesia.conf
      - ./conf/certs/cacert.pem:/opt/emqx/etc/certs/cacert.pem
      - ./conf/certs/cert.pem:/opt/emqx/etc/certs/cert.pem
      - ./conf/certs/key.pem:/opt/emqx/etc/certs/key.pem
      - ./conf/emqx-1/emqx.conf:/opt/emqx/etc/emqx.conf
    environment:
      - EMQX_NODE_NAME=emqx-1@172.20.7.3

  emqx-2:
    image: emqx/emqx:4.3.15
    container_name: dev_study_emqx-2
    restart: always
    networks:
      dev_net:
        ipv4_address: "172.20.7.4"
    ports:
      - 9111:4371
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/loaded/loaded_plugins:/opt/emqx/data/loaded_plugins
      - ./conf/plugins/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
      - ./conf/plugins/emqx_auth_jwt.conf:/opt/emqx/etc/plugins/emqx_auth_jwt.conf
      - ./conf/plugins/emqx_auth_mnesia.conf:/opt/emqx/etc/plugins/emqx_auth_mnesia.conf
      - ./conf/certs/cacert.pem:/opt/emqx/etc/certs/cacert.pem
      - ./conf/certs/cert.pem:/opt/emqx/etc/certs/cert.pem
      - ./conf/certs/key.pem:/opt/emqx/etc/certs/key.pem
      - ./conf/emqx-2/emqx.conf:/opt/emqx/etc/emqx.conf
    environment:
      - EMQX_NODE_NAME=emqx-2@172.20.7.4

networks:
  dev_net:
    external: true
