version: '3.9'
services:

  storaged0:
    image: vesoft/nebula-storaged:v3.1.0
    container_name: nebula-storaged0
    command:
      - --meta_server_addrs=nebula-metad0:9559,nebula-metad1:9559,nebula-metad2:9559
      - --local_ip=nebula-storaged0
      - --ws_ip=nebula-storaged0
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    # restart: alyways
    networks:
      - nebula-net
    ports:
      - "9701:9779"
      - "9702:19779"
      - "9703:19780"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/storage0:/data/storage
      - ./logs/storage0:/logs
    environment:
      USER: root
    # depends_on:
    #   - metad0
    #   - metad1
    #   - metad2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://nebula-storaged0:19779/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    cap_add:
      - SYS_PTRACE

  storaged1:
    image: vesoft/nebula-storaged:v3.1.0
    container_name: nebula-storaged1
    command:
      - --meta_server_addrs=nebula-metad0:9559,nebula-metad1:9559,nebula-metad2:9559
      - --local_ip=nebula-storaged1
      - --ws_ip=nebula-storaged1
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    # restart: alyways
    networks:
      - nebula-net
    ports:
      - "9704:9779"
      - "9705:19779"
      - "9706:19780"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/storage1:/data/storage
      - ./logs/storage1:/logs
    environment:
      USER: root
    # depends_on:
    #   - metad0
    #   - metad1
    #   - metad2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://nebula-storaged1:19779/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    cap_add:
      - SYS_PTRACE

  storaged2:
    image: vesoft/nebula-storaged:v3.1.0
    container_name: nebula-storaged2
    command:
      - --meta_server_addrs=nebula-metad0:9559,nebula-metad1:9559,nebula-metad2:9559
      - --local_ip=nebula-storaged2
      - --ws_ip=nebula-storaged2
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/data/storage
      - --log_dir=/logs
      - --v=0
      - --minloglevel=0
    # restart: alyways
    networks:
      - nebula-net
    ports:
      - "9707:9779"
      - "9708:19779"
      - "9709:19780"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/storage2:/data/storage
      - ./logs/storage2:/logs
    environment:
      USER: root
    # depends_on:
    #   - metad0
    #   - metad1
    #   - metad2
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://nebula-storaged2:19779/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    cap_add:
      - SYS_PTRACE

networks:
  nebula-net:
    external: true

