version: "3.9"
services:
  db:
    image: mysql:8.0.26
    container_name: study_db
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
    networks:
      dev_net:
        ipv4_address: "172.24.0.3"
    restart: always
    ports:
      - 8563:3306
    environment:
      - TZ=Asia/Shanghai
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - MYSQL_DATABASE=study
      - MYSQL_ROOT_PASSWORD=study

networks:
  dev_net:
    external: true
