version: '3.9'
services:

  console:
    image: vesoft/nebula-console:v3.0.0
    container_name: nebula-console
    entrypoint: ""
    command:
      - sh
      - -c
      - |
        sleep 15 &&
        nebula-console -addr nebula-graphd0 -port 9669 -u root -p nebula -e 'ADD HOSTS "nebula-storaged0":9779,"nebula-storaged1":9779,"nebula-storaged2":9779' &&
        sleep 36000
    restart: always
    networks:
      dev_net:
        ipv4_address: "172.20.5.2"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    # depends_on:
    #   - graphd0
    #   - stoaraged0
    #   - stoaraged1
    #   - stoaraged2

networks:
  dev_net:
    external: true
