version: "3.9"
services:

  emqx:
    image: emqx/emqx:4.3.12
    container_name: dev_study_emqx
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/emqx/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./conf/emqx/vm.args:/opt/emqx/etc/vm.args
      - ./conf/emqx/emqx_auth_mnesia.conf:/opt/emqx/etc/plugins/emqx_auth_mnesia.conf
      - ./conf/emqx/loaded_plugins:/opt/emqx/data/loaded_plugins
    networks:
      custom_net:
        ipv4_address: "172.25.0.4"
    ports:
      - 8753:1883

networks:
  custom_net:
    external: true
